In [0]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
xy = np.loadtxt('/content/gdrive/My Drive/Colab Notebooks/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [5]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [6]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))



0 Cost:  21027.0 
Prediction:
 [[22.048063 ]
 [21.619785 ]
 [24.096693 ]
 [22.293016 ]
 [18.633898 ]
 [ 7.2669706]
 [12.331034 ]
 [ 3.1505105]
 [14.347936 ]
 [ 4.2534266]
 [14.485711 ]
 [10.678065 ]
 [28.804642 ]
 [29.298807 ]
 [11.237835 ]
 [18.64654  ]
 [31.189459 ]
 [13.344662 ]
 [28.84174  ]
 [25.662813 ]
 [15.084752 ]
 [16.798367 ]
 [15.924548 ]
 [31.361118 ]
 [24.986366 ]]
10 Cost:  95.97635 
Prediction:
 [[157.11063]
 [183.99283]
 [184.06302]
 [196.52917]
 [142.46275]
 [ 98.59757]
 [142.77237]
 [ 99.8778 ]
 [166.13176]
 [144.8915 ]
 [140.14996]
 [134.61139]
 [194.05147]
 [166.64041]
 [142.28706]
 [183.433  ]
 [161.97668]
 [169.89073]
 [186.37148]
 [166.61377]
 [168.04634]
 [169.14369]
 [161.75204]
 [167.48862]
 [193.25116]]
20 Cost:  94.25732 
Prediction:
 [[158.01505]
 [185.11975]
 [185.15112]
 [197.73499]
 [143.31499]
 [ 99.26259]
 [143.69463]
 [100.58784]
 [167.21953]
 [145.9485 ]
 [141.02908]
 [135.50377]
 [195.1551 ]
 [167.53082]
 [143.2218 ]
 [184.59265]
 [162.81184]
 [171