<a href="https://colab.research.google.com/github/Steven-A3/DeepLearningZeroToAllColab/blob/master/lab07-3-linear_regression_min_max(keras).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==2.0.0

     |████████████████████████████████| 86.3MB 72kB/s 
     |████████████████████████████████| 3.8MB 25.1MB/s 
     |████████████████████████████████| 450kB 49.8MB/s 
     |████████████████████████████████| 81kB 9.4MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalle

### 환경설정

In [48]:
import tensorflow as tf
import numpy as np
import pandas as pd

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

print("Tensorflow version:", tf.__version__)
tf.random.set_seed(777) # for reproducibility

Tensorflow version: 2.0.0


### 데이터
- **`np.array()`**: 파이썬 리스트를 입력 받아 넘파이 배열을 만듭니다

In [0]:
 xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

- **`type()`**: 전달된 변수의 자료구조형을 반환해줍니다

In [28]:
type(xy)

numpy.ndarray

#### 사용자 정의 함수 (User-defined function)
- **`np.min()`**: 최솟값을 반환해줍니다. 변수 이름 뒤 **`0`**을 넣으면 열의 최솟값을, **`1`**을 넣으면 행의 최솟값을 반환해줍니다.
- **`np.max()`**: 최댓값을 반환해줍니다.

In [0]:
def MinMaxScaler(data):
  numerator = data - np.min(data, 0)  # 분자
  denominator = np.max(data, 0) - np.min(data, 0)  # 분모

  # noise term prevents the zero division
  return numerator / (denominator + 1e-7)

In [30]:
xy1 = MinMaxScaler(xy)
print(xy1)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


#### 사이킷런의 **`MinMaxScaler()`** 사용

In [0]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()

In [35]:
xy = min_max_scaler.fit_transform(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


#### 데이터에서 y 변수를 분리

In [0]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

### **`케라스(Keras)`**를 활용한 모델
- **`Sequential`** 객체를 model 변수에 할당

In [52]:
model = Sequential()
type(model)

tensorflow.python.keras.engine.sequential.Sequential

- **`add()`** 함수를 활용하여 모델에 층을 추가

In [0]:
model.add(Dense(1, input_dim=4)) # x_data의 특성 개수가 4개이므로 input_dim은 4로 지정

- **`compile()`** 함수를 활용하여 모델 컴파일

In [0]:
model.compile(loss="mse", optimizer="sgd")

- **`summary()`** 함수를 활용하여 최종 모델 확인

In [55]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


- **`fit()`** 함수를 활용하여 모델 훈련

In [0]:
history = model.fit(x_data, y_data, verbose=0, epochs=1000)

- 모델 결과를 판다스 데이터프레임으로 변환하여 결과 확인

In [57]:
hist = pd.DataFrame(history.history)
hist["epoch"] = history.epoch
hist.tail()

loss  epoch
995  0.006247    995
996  0.006241    996
997  0.006235    997
998  0.006229    998
999  0.006223    999

- **`get_weights()`** 함수로 가중치 행렬(W)과 절편(b) 확인

In [45]:
W, b = model.get_weights()
print("Weight:", W, "\nBias:", b)

Weight: [[ 0.6803703 ]
 [-0.44013187]
 [ 0.31738776]
 [ 0.82577986]] 
Bias: [-0.16503629]
